
'use client';

import { useState } from 'react';

interface Results {
  status?: number;
  result?: any;
  error?: string;
  reports?: {
    status?: number;
    result?: any;
    error?: string;
  };
}

export default function AuthDebug() {
  const [results, setResults] = useState<Results>({});
  const [loading, setLoading] = useState(false);

  const testAuth = async () => {
    setLoading(true);
    try {
      // Test authentication with admin credentials
      const response = await fetch('/api/auth', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          password: 'admin123',
          page: 'admin'
        }),
      });

      const result = await response.json();
      
      setResults({
        status: response.status,
        result: result
      });
    } catch (error) {
      setResults({
        error: error instanceof Error ? error.message : 'An unknown error occurred'
      });
    } finally {
      setLoading(false);
    }
  };

  const testReports = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/reports', {
        headers: {
          'Authorization': 'Bearer admin123',
          'X-Page': 'admin'
        }
      });

      const result = await response.json();
      
      setResults((prev: Results) => ({
        ...prev,
        reports: {
          status: response.status,
          result: result
        }
      }));
    } catch (error) {
      setResults((prev: Results) => ({
        ...prev,
        reports: {
          error: error instanceof Error ? error.message : 'An unknown error occurred'
        }
      }));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-4">Authentication Debug</h1>
      
      <div className="space-y-4">
        <button
          onClick={testAuth}
          disabled={loading}
          className="bg-blue-500 text-white px-4 py-2 rounded"
        >
          Test Auth API
        </button>
        
        <button
          onClick={testReports}
          disabled={loading}
          className="bg-green-500 text-white px-4 py-2 rounded ml-2"
        >
          Test Reports API
        </button>
      </div>

      <div className="mt-8">
        <h2 className="text-xl font-semibold mb-2">Results:</h2>
        <pre className="bg-gray-100 p-4 rounded overflow-auto">
          {JSON.stringify(results, null, 2)}
        </pre>
      </div>

      <div className="mt-8 p-4 bg-yellow-100 rounded">
        <h3 className="font-semibold">Required Supabase Table Structure:</h3>
        <pre className="mt-2">
{`CREATE TABLE public.userdata (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  password text null,
  page text null,
  role text null,
  constraint users_pkey primary key (id),
  constraint users_username_key unique (page)
);

INSERT INTO public.userdata (password, page, role) 
VALUES ('admin123', 'admin', 'admin');`}
        </pre>
      </div>
    </div>
  );
}
