
-- Create userdata table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.userdata (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  password text NULL,
  page text NULL,
  role text NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_username_key UNIQUE (page)
);

-- Insert default admin user
INSERT INTO public.userdata (password, page, role) 
VALUES ('admin123', 'admin', 'admin')
ON CONFLICT (page) DO UPDATE SET 
  password = EXCLUDED.password,
  role = EXCLUDED.role;

-- Insert default report user
INSERT INTO public.userdata (password, page, role) 
VALUES ('report123', 'report', 'user')
ON CONFLICT (page) DO UPDATE SET 
  password = EXCLUDED.password,
  role = EXCLUDED.role;
